using Backend.Api.Models.Agent;
using Newtonsoft.Json;

namespace Backend.Api.Models.OpenAI.Responses.Response;

/// <summary>
/// Base class for output items generated by the model
/// </summary>
public abstract class OutputItem
{
    public required string id { get; set; }
    public Status? status { get; set; }
    public required string type { get; set; }
}

