using Newtonsoft.Json;

namespace Backend.Api.Models.OpenAI.Responses.Response;

/// <summary>
/// Base class for output items generated by the model
/// </summary>
[JsonConverter(typeof(OutputItemConverter))]
public abstract class OutputItem
{
    public required string id { get; set; }
    public string? status { get; set; }
    public required string type { get; set; }
}

