namespace Backend.Api.Models.OpenAI.Requests;

/// <summary>
/// The output of a function tool call
/// </summary>
public class FunctionToolCallOutput : InputItem
{
    /// <summary>
    /// The unique ID of the function tool call generated by the model
    /// </summary>
    public required string call_id { get; set; }
    
    /// <summary>
    /// Text, image, or file output of the function tool call
    /// </summary>
    public required string output { get; set; }
}

