using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Backend.Api.Models.OpenAI.Requests;

/// <summary>
/// The role of a message input indicating instruction following hierarchy.
/// </summary>
[JsonConverter(typeof(StringEnumConverter))]
public enum MessageRole
{
    /// <summary>
    /// User message
    /// </summary>
    [EnumMember(Value = "user")]
    User,
    
    /// <summary>
    /// Assistant message (presumed to have been generated by the model in previous interactions)
    /// </summary>
    [EnumMember(Value = "assistant")]
    Assistant,
    
    /// <summary>
    /// System message
    /// </summary>
    [EnumMember(Value = "system")]
    System,
    
    /// <summary>
    /// Developer message (takes precedence over system and user messages)
    /// </summary>
    [EnumMember(Value = "developer")]
    Developer
}

